apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-bumbag-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: react-bumbag-app
  template:
    metadata:
      labels:
        app: react-bumbag-app
    spec:
      containers:
        - name: react-bumbag-app
          image: react-bumbag-app:0.0.1
          ports:
            - containerPort: 80
          volumeMounts:
            - name: site-data
              mountPath: /data
      volumes:
        - name: site-data
          emptyDir: {}
